version: 0.1

lang:
  - "zh-CN"
  - "en-US"
Base:
  prefix: "§6§lMAXMC §a§l>> "
  spawnloc:

AntiVoid:
  enable: false
SpeedUp:
  enable: false
  active_speed: 5
  switch_delay: 3
  sound: ORB_PICKUP
InvManager:
  enable: false
  no_drop: true
  clean: true
  join_items:
    enable: true
    items:
      menu:
        name: "§6MaxMc §f菜单"
        type: "COMPASS"
        amount: 1
        damage: 0
        slot: 4
        lore: |-
          §7右键可以打开神秘的传送门
        shiny: false
        enchantments:
          effiency: 1
ScoreBoard:
  enable: false
  refresh: 3
  title:
    - "MaxMc"
    - "MaxMc"
    - "MaxMc"
    - "MaxMc"
    - "MaxMc"
  content: |-
    的
PortalCommand:
  enable: false
  nether: ""
  end: ""
HidePlayer:
  enable: false
  switch_deplay: 3
  sound: ORB_PICKUP
